/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.BorderFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author 37119397
 */
public class VehiculosJFrame extends javax.swing.JFrame {
    Moto moto1, moto2;
    Auto auto1, auto2;
    
    int aceleracionA1 = 0;
    int aceleracionA2 = 0;
    int aceleracionM1 = 0;
    int aceleracionM2 = 0;
    /**
     * Creates new form VehiculosJFrame
     */
    public VehiculosJFrame() {
        initComponents();
       
     moto1 = new Moto("Celeste", "BajaJ PULSAR NS200", 135, "Nafta");
    moto2 = new Moto("Amarilla", "Yamaha R3", 173, "Nafta");
    auto1 = new Auto("Azul", "Hyundai i20", 190,"Nafta", 5);
    auto2 = new Auto("Rojo", "Fiat Toro", 188,"Nafta", 4);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoMoto1 = new javax.swing.JScrollPane();
        InfoVehiculo = new javax.swing.JTextArea();
        Clear = new javax.swing.JButton();
        ResultAceleracionA2 = new javax.swing.JLabel();
        ResultAceleracionA1 = new javax.swing.JLabel();
        ResultAceleracionM2 = new javax.swing.JLabel();
        ResultAceleracionM1 = new javax.swing.JLabel();
        AceleracionA2 = new javax.swing.JButton();
        AceleracionA1 = new javax.swing.JButton();
        AcelerarMoto2 = new javax.swing.JButton();
        AcelerarMoto1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Auto2 = new javax.swing.JButton();
        Auto1 = new javax.swing.JButton();
        Moto2 = new javax.swing.JButton();
        Moto1 = new javax.swing.JButton();
        ImgMoto2 = new javax.swing.JLabel();
        ImgAuto2 = new javax.swing.JLabel();
        ImgAuto1 = new javax.swing.JLabel();
        JLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoVehiculo.setColumns(20);
        InfoVehiculo.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        InfoVehiculo.setRows(5);
        InfoVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        InfoMoto1.setViewportView(InfoVehiculo);

        getContentPane().add(InfoMoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 350, 160));

        Clear.setBackground(new java.awt.Color(153, 255, 153));
        Clear.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Clear.setText("Clear");
        Clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 70, 60));

        ResultAceleracionA2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        ResultAceleracionA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153), 2));
        ResultAceleracionA2.setOpaque(true);
        getContentPane().add(ResultAceleracionA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 110, 40));

        ResultAceleracionA1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        ResultAceleracionA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153), 2));
        ResultAceleracionA1.setOpaque(true);
        getContentPane().add(ResultAceleracionA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, 40));

        ResultAceleracionM2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        ResultAceleracionM2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        ResultAceleracionM2.setOpaque(true);
        getContentPane().add(ResultAceleracionM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 100, 40));

        ResultAceleracionM1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        ResultAceleracionM1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        ResultAceleracionM1.setOpaque(true);
        getContentPane().add(ResultAceleracionM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 90, 40));

        AceleracionA2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        AceleracionA2.setText("AceleracionA2");
        AceleracionA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        AceleracionA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceleracionA2ActionPerformed(evt);
            }
        });
        getContentPane().add(AceleracionA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, 30));

        AceleracionA1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        AceleracionA1.setText("AceleracionA1");
        AceleracionA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        AceleracionA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AceleracionA1MousePressed(evt);
            }
        });
        AceleracionA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceleracionA1ActionPerformed(evt);
            }
        });
        getContentPane().add(AceleracionA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, 30));

        AcelerarMoto2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        AcelerarMoto2.setText("AcelerarM2");
        AcelerarMoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        AcelerarMoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcelerarMoto2ActionPerformed(evt);
            }
        });
        getContentPane().add(AcelerarMoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 90, 30));

        AcelerarMoto1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        AcelerarMoto1.setText("AcelerarM1");
        AcelerarMoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        AcelerarMoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcelerarMoto1ActionPerformed(evt);
            }
        });
        getContentPane().add(AcelerarMoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Auto 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel3.setText("Auto 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel2.setText("Moto 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel1.setText("Moto 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 60, 20));

        Auto2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Auto2.setText("Auto 2");
        Auto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));
        Auto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Auto2ActionPerformed(evt);
            }
        });
        getContentPane().add(Auto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 70, 30));

        Auto1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Auto1.setText("Auto 1");
        Auto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));
        Auto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Auto1ActionPerformed(evt);
            }
        });
        getContentPane().add(Auto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 70, 30));

        Moto2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Moto2.setText("Moto 2");
        Moto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        Moto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moto2ActionPerformed(evt);
            }
        });
        getContentPane().add(Moto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 30));

        Moto1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Moto1.setText("Moto 1");
        Moto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        Moto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moto1ActionPerformed(evt);
            }
        });
        getContentPane().add(Moto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 30));

        ImgMoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moto9.jpg"))); // NOI18N
        ImgMoto2.setText("jLabel1");
        getContentPane().add(ImgMoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 150, 90));

        ImgAuto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Auto8.jpg"))); // NOI18N
        ImgAuto2.setText("jLabel1");
        getContentPane().add(ImgAuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 368, 180, 90));

        ImgAuto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Auto6.jpg"))); // NOI18N
        ImgAuto1.setText("jLabel1");
        getContentPane().add(ImgAuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 190, 100));

        JLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moto7.jpg"))); // NOI18N
        JLabel5.setText("jLabel1");
        getContentPane().add(JLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 341, 110, 170));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo5.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 920, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Moto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moto1ActionPerformed
     InfoVehiculo.setText(moto1.mostrarDatos());
    }//GEN-LAST:event_Moto1ActionPerformed

    private void Moto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moto2ActionPerformed
     InfoVehiculo.setText(moto2.mostrarDatos());
    }//GEN-LAST:event_Moto2ActionPerformed

    private void Auto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Auto1ActionPerformed
       InfoVehiculo.setText(auto1.mostrarDatos());
    }//GEN-LAST:event_Auto1ActionPerformed

    private void Auto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Auto2ActionPerformed
        InfoVehiculo.setText(auto2.mostrarDatos());
    }//GEN-LAST:event_Auto2ActionPerformed

    private void AceleracionA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceleracionA1ActionPerformed
     aceleracionA1++;  // Aumenta la aceleración
    ResultAceleracionA1.setText(aceleracionA1 + " km/h");
    }//GEN-LAST:event_AceleracionA1ActionPerformed

    private void AcelerarMoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcelerarMoto1ActionPerformed
       aceleracionM1++;  // Aumenta la aceleración
    ResultAceleracionM1.setText(aceleracionM1 + " km/h");
    }//GEN-LAST:event_AcelerarMoto1ActionPerformed

    private void AceleracionA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceleracionA2ActionPerformed
       aceleracionA2++;  // Aumenta la aceleración
    ResultAceleracionA2.setText(aceleracionA2 + " km/h");
    }//GEN-LAST:event_AceleracionA2ActionPerformed

    private void AcelerarMoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcelerarMoto2ActionPerformed
     aceleracionM2++;  // Aumenta la aceleración
    ResultAceleracionM2.setText(aceleracionM2 + " km/h"); 
    }//GEN-LAST:event_AcelerarMoto2ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
     // Limpiar resultados
    ResultAceleracionA1.setText("");
    ResultAceleracionA2.setText("");
    ResultAceleracionM1.setText("");
    ResultAceleracionM2.setText("");

    // Limpiar el TextArea
    InfoVehiculo.setText("");

    // Reiniciar aceleración
    aceleracionA1 = 0;
    aceleracionA2 = 0;
    aceleracionM1 = 0;
    aceleracionM2 = 0;

    }//GEN-LAST:event_ClearActionPerformed

    private void AceleracionA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceleracionA1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceleracionA1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VehiculosJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceleracionA1;
    private javax.swing.JButton AceleracionA2;
    private javax.swing.JButton AcelerarMoto1;
    private javax.swing.JButton AcelerarMoto2;
    private javax.swing.JButton Auto1;
    private javax.swing.JButton Auto2;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel ImgAuto1;
    private javax.swing.JLabel ImgAuto2;
    private javax.swing.JLabel ImgMoto2;
    private javax.swing.JScrollPane InfoMoto1;
    private javax.swing.JTextArea InfoVehiculo;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JButton Moto1;
    private javax.swing.JButton Moto2;
    private javax.swing.JLabel ResultAceleracionA1;
    private javax.swing.JLabel ResultAceleracionA2;
    private javax.swing.JLabel ResultAceleracionM1;
    private javax.swing.JLabel ResultAceleracionM2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}